// Generated by spider on 2022-03-14 23:06:47.458666

class AssetsImages {
  AssetsImages._();

  static const String corey = 'assets/images/corey.png';
  static const String rectangle10 = 'assets/images/Rectangle 10.png';
  static const String ahmad = 'assets/images/ahmad.png';
  static const String rectangle12 = 'assets/images/Rectangle 12.png';
  static const String rectangle14 = 'assets/images/Rectangle 14.png';
  static const String rectangle6 = 'assets/images/Rectangle 6.png';
  static const String rectangle9 = 'assets/images/Rectangle 9.png';
  static const String rectangle8 = 'assets/images/Rectangle 8.png';
  static const String rectangle7 = 'assets/images/Rectangle 7.png';
  static const String tina = 'assets/images/tina.png';
  static const String cristofer = 'assets/images/cristofer.png';
  static const String rectangle11 = 'assets/images/Rectangle 11.png';
  static const String rectangle13 = 'assets/images/Rectangle 13.png';
}
